trigger:
  branches:
    include:
      - dev
      - main
  paths:
    include:
      - aks-deploy-from-acr.yaml
      - aks-deploy-from-acr-prod.yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DevDeployment
  displayName: Deploy to Dev
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
  - job: Deploy
    displayName: Deploy to Dev AKS
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: 'aks-deploy-from-acr.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: MainDeployment
  displayName: Deploy to Prod
  condition: eq(variables['Build.SourceBranchName'], 'main')
  jobs:
  - job: Deploy
    displayName: Deploy to Prod AKS
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: 'aks-deploy-from-acr-prod.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
