trigger:
  branches:
    include:
      - dev
      - main
  paths:
    include:
      - aks-deploy-from-acr-dev.yaml
      - aks-deploy-from-acr-prod.yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DevDeployment
  displayName: Deploy to Dev
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
  - job: Deploy
    displayName: Deploy to Dev AKS
    steps:
    - download: current  # Download the latest artifacts from the build pipeline
      artifact: drop
    - script: |
        echo "Using the latest image tag from build artifacts: $(imageTag)"
        sed -i 's|#{Build.BuildId}#|$(imageTag)|g' $(Pipeline.Workspace)/drop/aks-deploy-from-acr-dev.yaml

- stage: MainDeployment
  displayName: Deploy to Prod
  condition: eq(variables['Build.SourceBranchName'], 'main')
  jobs:
  - job: Deploy
    displayName: Deploy to Prod AKS
    steps:
    - download: current  # Download the latest artifacts from the build pipeline
      artifact: drop
    - script: |
        echo "Using the latest image tag from build artifacts: $(imageTag)"
        sed -i 's|#{Build.BuildId}#|$(imageTag)|g' $(Pipeline.Workspace)/drop/aks-deploy-from-acr-prod.yaml
